/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


public class BirthdayPackages extends javax.swing.JFrame {

    /**
     * Creates new form BirthdayPackagesFrame
     */
    public BirthdayPackages() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();
        jButtonBoooking = new javax.swing.JButton();
        jButtonCalendar = new javax.swing.JButton();
        jButtonPackages = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 125));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 222, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(205, 133, 63));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Birthday Packages");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 130, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1040, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Food Menu", "Pizza, Hot Dogs, Soft Drinks", "Pizza, Sandwiches, Soft Drinks, Cake", "Pizza, Sandwiches, Custom Cake, Kids' Buffet"},
                {"Seating", "20 kids chairs, 10 adult chairs", "40 chairs, kid-friendly layout", "60 chairs, themed kid and adult sections"},
                {"Tables", "4 tables, disposable covers", "6 tables, colored covers", "8 tables, themed covers and centerpieces"},
                {"Decor", "Basic balloons", "Balloon decorations, minimal theme decor", "Themed decor, balloon arch, stage decoration"},
                {"Tableware", "Disposable plates and cups", "Themed plates and cups", "Premium themed plates, cups, and table settings"},
                {"Laborers", "2 service staff", "4 service staff", "6 service staff"},
                {"Amenities", "Basic setup", "Themed tableware, small gift bags", "Full theme setup, gift bags, kids’ entertainer"},
                {"Additional Options", "None", "Small cake table, backdrop for photos", "Photobooth, entertainment options (clown, magician)"},
                {"Price Estimate", "$200", "$400", "$700"}
            },
            new String [] {
                "Packages", "Basic Birthtday", "Standard Birthday", "Premium Birthday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setCellSelectionEnabled(true);
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(35);
        jTable1.setSelectionBackground(new java.awt.Color(205, 133, 63));
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 60, 1040, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1080, 440));

        jPanel2.setBackground(new java.awt.Color(210, 180, 140));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Castellar", 3, 36)); // NOI18N
        jLabel1.setText("palates");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 60));

        jLabel2.setFont(new java.awt.Font("Castellar", 3, 36)); // NOI18N
        jLabel2.setText("&  Plates");
        jLabel2.setPreferredSize(new java.awt.Dimension(176, 43));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 60));

        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonHome.setText("HOME");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 160, 40));

        jButtonBoooking.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonBoooking.setText("BOOKING");
        jButtonBoooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBoookingActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBoooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 160, 40));

        jButtonCalendar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonCalendar.setText("CALENDAR");
        jPanel2.add(jButtonCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 160, 40));

        jButtonPackages.setBackground(new java.awt.Color(205, 133, 63));
        jButtonPackages.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPackages.setText("PACKAGES");
        jButtonPackages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPackagesActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPackages, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 160, 40));
        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, -10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBoookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBoookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBoookingActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonPackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPackagesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new PackagesFrame().setVisible(true);
    }//GEN-LAST:event_jButtonPackagesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BirthdayPackages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BirthdayPackages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BirthdayPackages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BirthdayPackages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BirthdayPackages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBoooking;
    private javax.swing.JButton jButtonCalendar;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonPackages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
