
package GUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class LaborersFrame extends javax.swing.JFrame {

    /**
     * Creates new form LaborersFrame
     */
    public LaborersFrame() {
        initComponents();
        loadLaborerToTable();
        
    }
    
   private void loadLaborerToTable() {
    try {
        // Establish the database connection
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/css_db", "root", "");

        // Query to fetch laborer and booking details excluding Paid status
        String query = "SELECT l.Name, l.PhoneNumber, l.Role, b.Theme,b.BookingId, b.EventDate, l.HourlyRate, " +
                       "TIMESTAMPDIFF(HOUR, b.TimeStart, b.TimeEnd) AS total_hours, " +
                       "bl.StatusPay, " +
                       "(TIMESTAMPDIFF(HOUR, b.TimeStart, b.TimeEnd) * l.HourlyRate) AS TotalPay " +
                       "FROM laborer l " +
                       "INNER JOIN booking_laborer bl ON l.LaborerID = bl.LaborerID " +
                       "INNER JOIN booking b ON bl.BookingId = b.BookingId " +
                       "WHERE bl.StatusPay != 'Paid'"; // Exclude records with Paid status

        PreparedStatement ps = con.prepareStatement(query);
        ResultSet rs = ps.executeQuery();

        // Create a DefaultTableModel
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) LaborerTable.getModel();
        model.setRowCount(0); // Clear existing rows

        // Iterate through the result set
        while (rs.next()) {
            // Add row to the model
            model.addRow(new Object[]{
                rs.getString("Name"), // Laborer Name
                rs.getString("PhoneNumber"), // Laborer PhoneNumber
                rs.getString("Role"), // Laborer Role
                rs.getInt("BookingId"), // Booking ID
                rs.getString("Theme"), // Event Theme
                rs.getString("EventDate"), // Event Date
                rs.getDouble("HourlyRate"), // Laborer Hourly Rate
                rs.getDouble("TotalPay"), // Total Pay
                rs.getString("StatusPay") // Payment Status
            });
        }

        // Close connections
        rs.close();
        ps.close();
        con.close();

    } catch (Exception ex) {
        // Print full stack trace for debugging
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading laborers: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelLaborerDetails = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        addLaborer = new javax.swing.JButton();
        SearchLaborer = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        LaborerTable = new javax.swing.JTable();
        Update = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHourlyRate = new javax.swing.JTextField();
        txtLaborerId = new javax.swing.JTextField();
        cmbStatusPay = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnCalendar = new javax.swing.JButton();
        BtnPackages = new javax.swing.JButton();
        BtnBooking = new javax.swing.JButton();
        BtnHome = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BtnLaborer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 125));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 222, 179));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLaborerDetails.setBackground(new java.awt.Color(210, 180, 140));
        jPanelLaborerDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Laborer Id");
        jPanelLaborerDetails.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Hourly Rate:");
        jPanelLaborerDetails.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 90, 20));
        jPanelLaborerDetails.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 300, -1));
        jPanelLaborerDetails.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 300, -1));

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WaitStaff", " " }));
        jPanelLaborerDetails.add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 150, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Status pay:");
        jPanelLaborerDetails.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 90, 20));

        addLaborer.setBackground(new java.awt.Color(205, 133, 63));
        addLaborer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addLaborer.setText("Add Laborer");
        addLaborer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLaborerActionPerformed(evt);
            }
        });
        jPanelLaborerDetails.add(addLaborer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 120, 40));

        SearchLaborer.setBackground(new java.awt.Color(205, 133, 63));
        SearchLaborer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SearchLaborer.setText("Search");
        SearchLaborer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchLaborerActionPerformed(evt);
            }
        });
        jPanelLaborerDetails.add(SearchLaborer, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 80, 40));

        LaborerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Phone Number", "Role", "EventID", "Event", "Date", "HourlyRate", "TotalPay", "StatusPay"
            }
        ));
        LaborerTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(LaborerTable);

        jScrollPane6.setViewportView(jScrollPane5);

        jPanelLaborerDetails.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 1010, 230));

        Update.setBackground(new java.awt.Color(205, 133, 63));
        Update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanelLaborerDetails.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 80, 40));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Not Active" }));
        jPanelLaborerDetails.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 150, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Role:");
        jPanelLaborerDetails.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 37, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Phone:");
        jPanelLaborerDetails.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 48, 20));

        txtHourlyRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHourlyRateActionPerformed(evt);
            }
        });
        jPanelLaborerDetails.add(txtHourlyRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 200, -1));
        jPanelLaborerDetails.add(txtLaborerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 300, -1));

        cmbStatusPay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Unpaid", "Paid" }));
        jPanelLaborerDetails.add(cmbStatusPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 150, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Status:");
        jPanelLaborerDetails.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 60, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Name:");
        jPanelLaborerDetails.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        jPanel1.add(jPanelLaborerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1080, 440));

        jPanel2.setBackground(new java.awt.Color(210, 180, 140));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCalendar.setBackground(new java.awt.Color(210, 180, 140));
        BtnCalendar.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        BtnCalendar.setText("CALENDAR");
        BtnCalendar.setBorder(null);
        BtnCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalendarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 140, 40));

        BtnPackages.setBackground(new java.awt.Color(210, 180, 140));
        BtnPackages.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        BtnPackages.setText("PACKAGES");
        BtnPackages.setBorder(null);
        BtnPackages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPackagesActionPerformed(evt);
            }
        });
        jPanel2.add(BtnPackages, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 140, 40));

        BtnBooking.setBackground(new java.awt.Color(210, 180, 140));
        BtnBooking.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        BtnBooking.setText("BOOKING");
        BtnBooking.setBorder(null);
        BtnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBookingActionPerformed(evt);
            }
        });
        jPanel2.add(BtnBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 140, 40));

        BtnHome.setBackground(new java.awt.Color(205, 133, 63));
        BtnHome.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        BtnHome.setText("HOME");
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(BtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 140, 40));

        jLabel13.setFont(new java.awt.Font("Castellar", 3, 36)); // NOI18N
        jLabel13.setText("PALATES  ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 60));

        jLabel14.setFont(new java.awt.Font("Castellar", 3, 36)); // NOI18N
        jLabel14.setText("&   plates");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 60));

        BtnLaborer.setBackground(new java.awt.Color(210, 180, 140));
        BtnLaborer.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        BtnLaborer.setText("LABOR");
        BtnLaborer.setBorder(null);
        BtnLaborer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaborerActionPerformed(evt);
            }
        });
        jPanel2.add(BtnLaborer, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 140, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalendarActionPerformed
        BtnCalendar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                ReservationCalendar calendar = new ReservationCalendar();
                calendar.setVisible(true);
                calendar.setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_BtnCalendarActionPerformed

    private void BtnPackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPackagesActionPerformed
        BtnPackages.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                PackagesFrame packages = new PackagesFrame();
                packages.setVisible(true);
                packages.setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_BtnPackagesActionPerformed

    private void BtnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBookingActionPerformed
        BtnBooking.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                BookingFrame bookingF = new BookingFrame();
                bookingF.setVisible(true);
                bookingF.setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_BtnBookingActionPerformed

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        BtnHome.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                HomeFrame home = new HomeFrame();
                home.setVisible(true);
                home.setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnLaborerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaborerActionPerformed
        BtnLaborer.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                LaborersFrame laborer = new LaborersFrame();
                laborer.setVisible(true);
                laborer .setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_BtnLaborerActionPerformed

    private void addLaborerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLaborerActionPerformed
    String name = txtName.getText().trim();
    String phone = txtPhone.getText().trim();
    String role = cmbRole.getSelectedItem().toString();
    String status = cmbStatus.getSelectedItem().toString();
    String hourlyRateStr = txtHourlyRate.getText().trim();

    // Validate input
    if (name.isEmpty() || phone.isEmpty() || hourlyRateStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all the details.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    double hourlyRate;
    try {
        hourlyRate = Double.parseDouble(hourlyRateStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid hourly rate. Please enter a numeric value.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Database insertion
    String query = "INSERT INTO laborer (Name, PhoneNumber, Role, Status, HourlyRate) VALUES (?, ?, ?, ?, ?)";
    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/css_db", "root", "");
         PreparedStatement ps = con.prepareStatement(query)) {

        ps.setString(1, name);
        ps.setString(2, phone);
        ps.setString(3, role);
        ps.setString(4, status);
        ps.setDouble(5, hourlyRate);

        int rowsInserted = ps.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Laborer added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add laborer.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_addLaborerActionPerformed

    private void SearchLaborerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchLaborerActionPerformed
    String laborerIdStr = txtLaborerId.getText().trim(); // Laborer ID input field (for searching by ID)
    String name = txtName.getText().trim(); // Name input field (for searching by name)

    // Validate input
    if (laborerIdStr.isEmpty() && name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter either a Laborer ID or Name to search.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    StringBuilder query = new StringBuilder("SELECT * FROM laborer WHERE");

    // Add conditions based on the input provided by the user
    if (!laborerIdStr.isEmpty()) {
        query.append(" LaborerId = ?");
    }
    if (!name.isEmpty()) {
        if (!laborerIdStr.isEmpty()) {
            query.append(" OR");  // Use OR if both fields are provided
        }
        query.append(" Name LIKE ?");
    }

    try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/css_db", "root", "");
         PreparedStatement ps = con.prepareStatement(query.toString())) {

        int index = 1;

        // Set the parameters for the query
        if (!laborerIdStr.isEmpty()) {
            ps.setInt(index++, Integer.parseInt(laborerIdStr)); // Set LaborerId if provided
        }
        if (!name.isEmpty()) {
            ps.setString(index++, "%" + name + "%"); // Use LIKE for partial name matching
        }

        ResultSet rs = ps.executeQuery();

        // If a result is found, auto-fill the fields
        if (rs.next()) {
            txtLaborerId.setText(String.valueOf(rs.getInt("LaborerId")));  // Set LaborerId field
            txtName.setText(rs.getString("Name"));  // Set Name field
            txtPhone.setText(rs.getString("PhoneNumber"));  // Set Phone field
            cmbRole.setSelectedItem(rs.getString("Role"));  // Set Role ComboBox
            cmbStatus.setSelectedItem(rs.getString("Status"));  // Set Status ComboBox
            txtHourlyRate.setText(String.valueOf(rs.getDouble("HourlyRate")));  // Set HourlyRate field
        } else {
            JOptionPane.showMessageDialog(this, "No laborer found with the given details.", "Search Result", JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_SearchLaborerActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
     String name = txtName.getText().trim();
String phone = txtPhone.getText().trim();
String role = cmbRole.getSelectedItem().toString();
String status = cmbStatus.getSelectedItem().toString(); // This is for "Active" or "Inactive"
String statusPay = cmbStatusPay.getSelectedItem().toString(); // This is for "Paid" or "Unpaid"
String hourlyRateStr = txtHourlyRate.getText().trim();
String laborerIdStr = txtLaborerId.getText().trim(); // Assuming txtLaborerId is the text field for Laborer ID

// Validate input
if (name.isEmpty() || phone.isEmpty() || hourlyRateStr.isEmpty() || laborerIdStr.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all the details.", "Input Error", JOptionPane.ERROR_MESSAGE);
    return;
}

int laborerId;
try {
    laborerId = Integer.parseInt(laborerIdStr); // Convert Laborer ID to integer
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Invalid Laborer ID. Please enter a numeric value.", "Input Error", JOptionPane.ERROR_MESSAGE);
    return;
}

double hourlyRate;
try {
    hourlyRate = Double.parseDouble(hourlyRateStr); // Convert hourly rate to double
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Invalid hourly rate. Please enter a numeric value.", "Input Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Query to update the laborer's personal information
String updateLaborerQuery = "UPDATE laborer SET Name = ?, PhoneNumber = ?, Role = ?, Status = ?, HourlyRate = ? WHERE LaborerID = ?";

try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/css_db", "root", "");
     PreparedStatement ps = con.prepareStatement(updateLaborerQuery)) {

    // Set parameters for the update query
    ps.setString(1, name);
    ps.setString(2, phone);
    ps.setString(3, role);
    ps.setString(4, status); // "Active" or "Inactive"
    ps.setDouble(5, hourlyRate);
    ps.setInt(6, laborerId);

    // Execute the update
    int rowsUpdated = ps.executeUpdate();

    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(this, "Laborer information updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Failed to update laborer information. Please check the Laborer ID.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    loadLaborerToTable(); // Reload the table after update

} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    ex.printStackTrace();
}

    }//GEN-LAST:event_UpdateActionPerformed

    private void txtHourlyRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHourlyRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHourlyRateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaborersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaborersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaborersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaborersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaborersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBooking;
    private javax.swing.JButton BtnCalendar;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnLaborer;
    private javax.swing.JButton BtnPackages;
    private javax.swing.JTable LaborerTable;
    private javax.swing.JButton SearchLaborer;
    private javax.swing.JButton Update;
    private javax.swing.JButton addLaborer;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbStatusPay;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelLaborerDetails;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField txtHourlyRate;
    private javax.swing.JTextField txtLaborerId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
