/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
/**
 *
 * @author Ivan
 */
public class PackagesFrame extends javax.swing.JFrame {

    /**
     * Creates new form PackagesFrame
     */
    public PackagesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BtnCalendar = new javax.swing.JButton();
        BtnPackages = new javax.swing.JButton();
        BtnBooking = new javax.swing.JButton();
        BtnHome = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BtnLaborer = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        BtnReport = new javax.swing.JButton();
        P1F1 = new javax.swing.JButton();
        BasicBaptism = new javax.swing.JButton();
        BasicBirthday = new javax.swing.JButton();
        BasicWedding = new javax.swing.JButton();
        P1F2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        P1F3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        StandardBaptism = new javax.swing.JButton();
        PremiumBaptism = new javax.swing.JButton();
        StandardBirthday = new javax.swing.JButton();
        PremiumBirthday = new javax.swing.JButton();
        StandardWedding = new javax.swing.JButton();
        PremiumWedding = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1080, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(210, 180, 140));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCalendar.setBackground(new java.awt.Color(210, 180, 140));
        BtnCalendar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCalendar.setText("CALENDAR");
        BtnCalendar.setBorder(null);
        BtnCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalendarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 120, 40));

        BtnPackages.setBackground(new java.awt.Color(210, 180, 140));
        BtnPackages.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnPackages.setText("PACKAGES");
        BtnPackages.setBorder(null);
        BtnPackages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPackagesActionPerformed(evt);
            }
        });
        jPanel2.add(BtnPackages, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 120, 40));

        BtnBooking.setBackground(new java.awt.Color(210, 180, 140));
        BtnBooking.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnBooking.setText("BOOKING");
        BtnBooking.setBorder(null);
        BtnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBookingActionPerformed(evt);
            }
        });
        jPanel2.add(BtnBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 120, 40));

        BtnHome.setBackground(new java.awt.Color(210, 180, 140));
        BtnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnHome.setText("HOME");
        BtnHome.setBorder(null);
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(BtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 120, 40));

        jLabel13.setFont(new java.awt.Font("Castellar", 3, 30)); // NOI18N
        jLabel13.setText("PALATES  ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 60));

        jLabel14.setFont(new java.awt.Font("Castellar", 3, 30)); // NOI18N
        jLabel14.setText("&   plates");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 60));

        BtnLaborer.setBackground(new java.awt.Color(205, 133, 63));
        BtnLaborer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnLaborer.setText("LABOR");
        BtnLaborer.setBorder(null);
        BtnLaborer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaborerActionPerformed(evt);
            }
        });
        jPanel2.add(BtnLaborer, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 120, 40));

        logout.setBackground(new java.awt.Color(210, 180, 140));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout (1).png"))); // NOI18N
        logout.setBorder(null);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 30, 40, 40));

        BtnReport.setBackground(new java.awt.Color(210, 180, 140));
        BtnReport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnReport.setText("REPORT");
        BtnReport.setBorder(null);
        BtnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReportActionPerformed(evt);
            }
        });
        jPanel2.add(BtnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 120, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 90));

        P1F1.setBackground(new java.awt.Color(210, 180, 140));
        P1F1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        P1F1.setText("Serenity Farewell ");
        P1F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1F1ActionPerformed(evt);
            }
        });
        getContentPane().add(P1F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 410, 40));

        BasicBaptism.setBackground(new java.awt.Color(210, 180, 140));
        BasicBaptism.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BasicBaptism.setText("Sacred start package");
        BasicBaptism.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasicBaptismActionPerformed(evt);
            }
        });
        getContentPane().add(BasicBaptism, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 410, 40));

        BasicBirthday.setBackground(new java.awt.Color(210, 180, 140));
        BasicBirthday.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BasicBirthday.setText("Essential Package");
        BasicBirthday.setBorder(null);
        BasicBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasicBirthdayActionPerformed(evt);
            }
        });
        getContentPane().add(BasicBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 360, 40));

        BasicWedding.setBackground(new java.awt.Color(210, 180, 140));
        BasicWedding.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BasicWedding.setText("Timeless Love Package");
        BasicWedding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasicWeddingActionPerformed(evt);
            }
        });
        getContentPane().add(BasicWedding, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 360, 40));

        P1F2.setBackground(new java.awt.Color(210, 180, 140));
        P1F2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        P1F2.setText("Timeless Remembrance");
        P1F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1F2ActionPerformed(evt);
            }
        });
        getContentPane().add(P1F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 410, 40));

        jLabel19.setFont(new java.awt.Font("Castellar", 3, 48)); // NOI18N
        jLabel19.setText("F");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 40, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 32)); // NOI18N
        jLabel21.setText("uneral");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 170, -1));

        jLabel20.setFont(new java.awt.Font("Castellar", 3, 48)); // NOI18N
        jLabel20.setText("b");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 40, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 32)); // NOI18N
        jLabel22.setText("aptism");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 298, 170, -1));

        P1F3.setBackground(new java.awt.Color(210, 180, 140));
        P1F3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        P1F3.setText("Opulent Remembrance Package");
        P1F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1F3ActionPerformed(evt);
            }
        });
        getContentPane().add(P1F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 410, 40));

        jLabel23.setFont(new java.awt.Font("Castellar", 3, 48)); // NOI18N
        jLabel23.setText("b");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 40, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 32)); // NOI18N
        jLabel24.setText("irthday");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 170, -1));

        jLabel25.setFont(new java.awt.Font("Castellar", 3, 48)); // NOI18N
        jLabel25.setText("w");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 60, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 32)); // NOI18N
        jLabel26.setText("edding");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 170, -1));

        StandardBaptism.setBackground(new java.awt.Color(210, 180, 140));
        StandardBaptism.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StandardBaptism.setText("Graceful Celebration Package");
        StandardBaptism.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardBaptismActionPerformed(evt);
            }
        });
        getContentPane().add(StandardBaptism, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 410, 40));

        PremiumBaptism.setBackground(new java.awt.Color(210, 180, 140));
        PremiumBaptism.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PremiumBaptism.setText("Heavenly Blessings Package");
        PremiumBaptism.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PremiumBaptismActionPerformed(evt);
            }
        });
        getContentPane().add(PremiumBaptism, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 410, 40));

        StandardBirthday.setBackground(new java.awt.Color(210, 180, 140));
        StandardBirthday.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StandardBirthday.setText("Festive Gathering Package");
        StandardBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardBirthdayActionPerformed(evt);
            }
        });
        getContentPane().add(StandardBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 360, -1));

        PremiumBirthday.setBackground(new java.awt.Color(210, 180, 140));
        PremiumBirthday.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PremiumBirthday.setText("Royal Birthday Package");
        PremiumBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PremiumBirthdayActionPerformed(evt);
            }
        });
        getContentPane().add(PremiumBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 360, -1));

        StandardWedding.setBackground(new java.awt.Color(210, 180, 140));
        StandardWedding.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        StandardWedding.setText("Elegant Romance Package");
        StandardWedding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardWeddingActionPerformed(evt);
            }
        });
        getContentPane().add(StandardWedding, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 390, 360, -1));

        PremiumWedding.setBackground(new java.awt.Color(210, 180, 140));
        PremiumWedding.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PremiumWedding.setText("Luxurious Wedding Package");
        PremiumWedding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PremiumWeddingActionPerformed(evt);
            }
        });
        getContentPane().add(PremiumWedding, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 440, 360, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled design.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1080, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P1F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1F1ActionPerformed
        P1F1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               
                PackageF1 f1 = new PackageF1();
                f1.setVisible(true);
                f1.setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_P1F1ActionPerformed

    private void BtnCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalendarActionPerformed
        BtnCalendar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                ReservationCalendar calendar = new ReservationCalendar();
                calendar.setVisible(true);
                calendar.setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_BtnCalendarActionPerformed

    private void BtnPackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPackagesActionPerformed
        BtnPackages.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                PackagesFrame packages = new PackagesFrame();
                packages.setVisible(true);
                packages.setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_BtnPackagesActionPerformed

    private void BtnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBookingActionPerformed
        BtnBooking.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                BookingProcess booking = new BookingProcess();
                booking.setVisible(true);
                booking.setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_BtnBookingActionPerformed

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        BtnHome.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                HomeFrame home = new HomeFrame();
                home.setVisible(true);
                home.setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnLaborerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaborerActionPerformed
        BtnLaborer.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                LaborersTable laborer = new LaborersTable();
                laborer.setVisible(true);
                laborer .setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_BtnLaborerActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        logout.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // Show a confirmation dialog to the user before logging out
                int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?", "Log Out", JOptionPane.YES_NO_OPTION);

                // If the user selects "Yes" (confirm == 0), log out and dispose of the frame
                if (confirm == JOptionPane.YES_OPTION) {
                    dispose(); // Close the current LogIn frame
                    LogIn login = new LogIn();
                    login.setVisible(true); // Make the LogIn frame visible
                    login.setLocationRelativeTo(null); // Center the LogIn frame
                }
            }
        });
    }//GEN-LAST:event_logoutActionPerformed

    private void BtnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReportActionPerformed
        BtnReport.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dispose();
                Sales laborer = new Sales();
                laborer.setVisible(true);
                laborer .setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_BtnReportActionPerformed

    private void P1F2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1F2ActionPerformed
        P1F2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                PackageF2 F2 = new PackageF2();
                F2.setVisible(true);
                F2.setLocationRelativeTo(null); // Center the SignUP frame
            }
        });
    }//GEN-LAST:event_P1F2ActionPerformed

    private void BasicBaptismActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasicBaptismActionPerformed
        // TODO add your handling code here:
        BasicBaptism basicBaptismFrame = new BasicBaptism();
        basicBaptismFrame.setVisible(true);
        basicBaptismFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_BasicBaptismActionPerformed

    private void StandardBaptismActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardBaptismActionPerformed
        // TODO add your handling code here:
        StandardBaptism standardBaptismFrame = new StandardBaptism();
        standardBaptismFrame.setVisible(true);
        standardBaptismFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_StandardBaptismActionPerformed

    private void BasicBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasicBirthdayActionPerformed
        // TODO add your handling code here:
        BasicBirthday basicBirthdayFrame = new BasicBirthday();
        basicBirthdayFrame.setVisible(true);
        basicBirthdayFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_BasicBirthdayActionPerformed

    private void PremiumBaptismActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PremiumBaptismActionPerformed
        // TODO add your handling code here:
        PremiumBaptism premiumBaptismFrame = new PremiumBaptism();
        premiumBaptismFrame.setVisible(true);
        premiumBaptismFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_PremiumBaptismActionPerformed

    private void StandardWeddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardWeddingActionPerformed
        // TODO add your handling code here:
        StandardWedding standardWeddingFrame = new StandardWedding();
        standardWeddingFrame.setVisible(true);
        standardWeddingFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_StandardWeddingActionPerformed

    private void BasicWeddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasicWeddingActionPerformed
        // TODO add your handling code here:
        BasicWedding basicWeddingFrame = new BasicWedding();
        basicWeddingFrame.setVisible(true);
        basicWeddingFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_BasicWeddingActionPerformed

    private void P1F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1F3ActionPerformed
        // TODO add your handling code here:
        PackageF3 packageF3Frame = new PackageF3();
        packageF3Frame.setVisible(true);
        packageF3Frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_P1F3ActionPerformed

    private void StandardBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardBirthdayActionPerformed
        // TODO add your handling code here:
        StandardBirthday standardBirthdayFrame = new StandardBirthday();
        standardBirthdayFrame.setVisible(true);
        standardBirthdayFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_StandardBirthdayActionPerformed

    private void PremiumBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PremiumBirthdayActionPerformed
        // TODO add your handling code here:
        PremiumBirthday premiumBirthdayFrame = new PremiumBirthday();
        premiumBirthdayFrame.setVisible(true);
        premiumBirthdayFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_PremiumBirthdayActionPerformed

    private void PremiumWeddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PremiumWeddingActionPerformed
        // TODO add your handling code here:
        PremiumWedding premiumWeddingFrame = new PremiumWedding();
        premiumWeddingFrame.setVisible(true);
        premiumWeddingFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_PremiumWeddingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PackagesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PackagesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PackagesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PackagesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PackagesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BasicBaptism;
    private javax.swing.JButton BasicBirthday;
    private javax.swing.JButton BasicWedding;
    private javax.swing.JButton BtnBooking;
    private javax.swing.JButton BtnCalendar;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnLaborer;
    private javax.swing.JButton BtnPackages;
    private javax.swing.JButton BtnReport;
    private javax.swing.JButton P1F1;
    private javax.swing.JButton P1F2;
    private javax.swing.JButton P1F3;
    private javax.swing.JButton PremiumBaptism;
    private javax.swing.JButton PremiumBirthday;
    private javax.swing.JButton PremiumWedding;
    private javax.swing.JButton StandardBaptism;
    private javax.swing.JButton StandardBirthday;
    private javax.swing.JButton StandardWedding;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
