/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


public class PackagesFrame extends javax.swing.JFrame {

    /**
     * Creates new form PackagesFrame
     */
    public PackagesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonFuneralPack = new javax.swing.JButton();
        jButtonBaptismPack = new javax.swing.JButton();
        jButtonBdayPack = new javax.swing.JButton();
        jButtonWedPack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        Booking = new javax.swing.JButton();
        Calendar = new javax.swing.JButton();
        Packages = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 125));
        setMinimumSize(new java.awt.Dimension(1080, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 222, 179));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setMinimumSize(new java.awt.Dimension(1050, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonFuneralPack.setBackground(new java.awt.Color(210, 180, 140));
        jButtonFuneralPack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonFuneralPack.setText("Funeral Packages");
        jButtonFuneralPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuneralPackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFuneralPack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 320, 150));

        jButtonBaptismPack.setBackground(new java.awt.Color(210, 180, 140));
        jButtonBaptismPack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonBaptismPack.setText("Baptism Packages");
        jButtonBaptismPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaptismPackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBaptismPack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 320, 150));

        jButtonBdayPack.setBackground(new java.awt.Color(210, 180, 140));
        jButtonBdayPack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonBdayPack.setText("Birthday Packages");
        jButtonBdayPack.setBorder(null);
        jButtonBdayPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBdayPackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBdayPack, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 320, 150));

        jButtonWedPack.setBackground(new java.awt.Color(210, 180, 140));
        jButtonWedPack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonWedPack.setText("Wedding Packages");
        jButtonWedPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWedPackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonWedPack, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 320, 150));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1080, 440));

        jPanel2.setBackground(new java.awt.Color(210, 180, 140));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Castellar", 3, 36)); // NOI18N
        jLabel3.setText("PALATES");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 60));

        jLabel1.setFont(new java.awt.Font("Castellar", 3, 36)); // NOI18N
        jLabel1.setText("&   PLATES");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 60));

        Home.setBackground(new java.awt.Color(210, 180, 140));
        Home.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Home.setText("HOME");
        jPanel2.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 160, 40));

        Booking.setBackground(new java.awt.Color(210, 180, 140));
        Booking.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Booking.setText("BOOKING");
        jPanel2.add(Booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 160, 40));

        Calendar.setBackground(new java.awt.Color(210, 180, 140));
        Calendar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Calendar.setText("CALENDAR");
        jPanel2.add(Calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 160, 40));

        Packages.setBackground(new java.awt.Color(205, 133, 63));
        Packages.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Packages.setText("PACKAGES");
        Packages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PackagesActionPerformed(evt);
            }
        });
        jPanel2.add(Packages, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 160, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFuneralPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuneralPackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FuneralPackages().setVisible(true);
    }//GEN-LAST:event_jButtonFuneralPackActionPerformed

    private void PackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PackagesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new PackagesFrame().setVisible(true);
    }//GEN-LAST:event_PackagesActionPerformed

    private void jButtonBdayPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBdayPackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new BirthdayPackages().setVisible(true);
    }//GEN-LAST:event_jButtonBdayPackActionPerformed

    private void jButtonBaptismPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaptismPackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new BaptismPackages().setVisible(true);
    }//GEN-LAST:event_jButtonBaptismPackActionPerformed

    private void jButtonWedPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWedPackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new WeddingPackages().setVisible(true);
    }//GEN-LAST:event_jButtonWedPackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PackagesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PackagesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PackagesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PackagesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PackagesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Booking;
    private javax.swing.JButton Calendar;
    private javax.swing.JButton Home;
    private javax.swing.JButton Packages;
    private javax.swing.JButton jButtonBaptismPack;
    private javax.swing.JButton jButtonBdayPack;
    private javax.swing.JButton jButtonFuneralPack;
    private javax.swing.JButton jButtonWedPack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
